set(FOMOD_INFO_DATA 
"<fomod> \n"
"	<Name>${PROJECT_NAME}</Name> \n"
"	<Author>${PROJECT_AUTHOR}</Author> \n"
"	<Version>${CMAKE_PROJECT_VERSION_MAJOR}.${CMAKE_PROJECT_VERSION_MINOR}.${CMAKE_PROJECT_VERSION_PATCH}.${CMAKE_PROJECT_VERSION_TWEAK}</Version> \n"
"	<Description>\n"
"   </Description> \n"
"	<Groups>\n"
"		<element>User Interface</element>\n"
"	</Groups> \n" 
"</fomod> \n"
)

set(FOMOD_MODULE_CONFIG
"<!-- Created with FOMOD Creation Tool 1.7.0.37 [http://www.nexusmods.com/fallout4/mods/6821] -->\n"
"<config xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://qconsulting.ca/fo3/ModConfig5.0.xsd\">\n"
"	<moduleName>dmenu</moduleName> \n"
"	<installSteps order=\"Explicit\"> \n"
"		<installStep name=\"Developer Options\"> \n"
"			<optionalFileGroups order=\"Explicit\"> \n"
"				<group name=\"Build Type\" type=\"SelectExactlyOne\">\n"
"					<plugins order=\"Explicit\"> \n"
"						<plugin name=\"Release\"> \n"
"							<description>Installs the Release Build: Highly recommended for most users, offering the highest performance.\n"
"\n"
"\n"
"\n"
"Maximum Optimization, No Debugging: This build is optimized for the best performance and does not include debugging information.</description>\n"
"							<conditionFlags> \n"
"								<flag name=\"release\">On</flag>\n"
"							</conditionFlags>\n"
"							<files> \n"
"								<file source=\"Plugin - Release\\${PROJECT_NAME}.dll\" destination=\"SKSE\\Plugins\\${PROJECT_NAME}.dll\"/>\n"
"							</files> \n"
"							<typeDescriptor> \n"
"								<type name=\"Recommended\"/>\n"
"							</typeDescriptor>\n"
"						</plugin> \n"
"						<plugin name=\"Debug\"> \n"
"							<description>Installs the Debug Build: Ideal for development and testing.\n"
"\n"
"\n"
"\n"
"No Optimization, Maximum Debugging: This build provides extensive debug information to assist in diagnosing issues.\n"
"\n"
"Crash Reporting: If the game crashes due to this SKSE plugin, please provide the details for troubleshooting.\n"
"\n"
"\n"
"Note: While I will review any reports, I cannot guarantee a fix for every bug or crash.</description> \n"
"							<conditionFlags> \n"
"								<flag name=\"debug\">On</flag>\n"
"							</conditionFlags>\n"
"							<files> \n"
"								<file source=\"Plugin - Debug\\${PROJECT_NAME}.dll\" destination=\"SKSE\\Plugins\\${PROJECT_NAME}.dll\"/> \n"
"								<file source=\"Plugin - Debug\\${PROJECT_NAME}.pdb\" destination=\"SKSE\\Plugins\\${PROJECT_NAME}.pdb\"/>\n"
"							</files> \n"
"							<typeDescriptor> \n"
"								<type name=\"Optional\"/>\n"
"							</typeDescriptor>\n"
"						</plugin> \n"
"						<plugin name=\"RelWithDebInfo\"> \n"
"							<description>Installs the RelWithDebInfo Build: Useful for development and testing with performance optimizations.\n"
"\n"
"Optimized Performance with Debug Information: This build includes optimizations along with debug information, making it suitable for troubleshooting performance issues.\n"
"\n"
"\n"
"Use if the Game Crashes(optional): If the game crashes due to this SKSE Plugin, send the details for investigation.\n"
"\n"
"\n"
"No Guaranteed Fix: While I'll do my best to help, I can't guarantee a fix for your bug or crash.</description> \n"
"							<conditionFlags> \n"
"								<flag name=\"RelWithDebInfo\">On</flag>\n"
"							</conditionFlags>\n"
"							<files> \n"
"								<file source=\"Plugin - RelWithDebInfo\\${PROJECT_NAME}.dll\" destination=\"SKSE\\Plugins\\${PROJECT_NAME}.dll\"/> \n"
"								<file source=\"Plugin - RelWithDebInfo\\${PROJECT_NAME}.pdb\" destination=\"SKSE\\Plugins\\${PROJECT_NAME}.pdb\"/>\n"
"							</files> \n"
"							<typeDescriptor> \n"
"								<type name=\"Optional\"/>\n"
"							</typeDescriptor>\n"
"						</plugin> \n"
"						<plugin name=\"MinSizeRel\"> \n"
"							<description>Installs the MinSizeRel Build: Ideal for users who need to minimize the size of the build while maintaining reasonable performance.\n"
"\n"
"\n"
"\n"
"Minimal Size with Performance: This build is optimized to reduce the executable size, making it suitable for environments with limited storage or distribution constraints.\n"
"</description> \n"
"							<conditionFlags> \n"
"								<flag name=\"MinSizeRel\">On</flag>\n"
"							</conditionFlags>\n"
"							<files> \n"
"								<file source=\"Plugin - MinSizeRel\\${PROJECT_NAME}.dll\" destination=\"SKSE\\Plugins\\${PROJECT_NAME}.dll\"/>\n"
"							</files>\n"
"							<typeDescriptor>\n"
"								<type name=\"Optional\"/>\n"
"							</typeDescriptor>\n"
"						</plugin> \n"
"					</plugins>\n"
"				</group> \n"
"			</optionalFileGroups>\n"
"		</installStep> \n"
"	</installSteps>\n"
"</config>\n"
"\n"
)

if( NOT DEFINED DISTRIBUTION_DIR )
	message(FATAL_ERROR "Variable ZIP_DIR is not Defined")
endif()

if(NOT DEFINED ENV{GITHUB_ENV})
	message(STATUS "GitHub environment not detected. Executing fomod xml file modification.")
    file(WRITE "${DISTRIBUTION_DIR}/fomod/info.xml" ${FOMOD_INFO_DATA})
	file(WRITE "${DISTRIBUTION_DIR}/fomod/ModuleConfig.xml" ${FOMOD_MODULE_CONFIG})
else()
	message(STATUS "GitHub environment detected. Skipping fomod xml file modification.")
endif()
